name: tiny_alert
description: Simple Flutter Alert with a simple design for fast coding.
version: 0.0.4
homepage: https://github.com/amdkholil/tiny-alert
repository: https://github.com/amdkholil/tiny-alert.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  assets:
    - lib/assets/
