name: tiny_alert
description: Simple Flutter Alert.
version: 0.0.3
homepage: https://github.com/amdkholil/tiny_alert
repository: https://github.com/amdkholil/tiny_alert

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - lib/assets/
